framework:
    http_client:
        scoped_clients:
            sylius_admin_mcp_server.http_client.api:
                base_uri: '%sylius_admin_mcp_server.api.base_uri%'
                verify_peer: '%env(bool:SYLIUS_ADMIN_MCP_SERVER_VERIFY_SSL)%'
                verify_host: '%env(bool:SYLIUS_ADMIN_MCP_SERVER_VERIFY_SSL)%'
                headers:
                    Accept: 'application/ld+json'
                    Content-Type: 'application/ld+json'
            sylius_admin_mcp_server.http_client.api_merge_patch:
                base_uri: '%sylius_admin_mcp_server.api.base_uri%'
                verify_peer: '%env(bool:SYLIUS_ADMIN_MCP_SERVER_VERIFY_SSL)%'
                verify_host: '%env(bool:SYLIUS_ADMIN_MCP_SERVER_VERIFY_SSL)%'
                headers:
                    Accept: 'application/ld+json'
                    Content-Type: 'application/merge-patch+json'
