sylius_twig_hooks:
    hooks:
        'sylius_admin.admin_user.create.content.form.sections.account':
            access_levels:
                template: '@SyliusAdminMcpServer/admin_user/form/sections/account/access_levels.html.twig'
                priority: -100

        'sylius_admin.admin_user.update.content.form.sections.account':
            access_levels:
                template: '@SyliusAdminMcpServer/admin_user/form/sections/account/access_levels.html.twig'
                priority: -100
