sylius_twig_hooks:
    hooks:
        'sylius_admin.admin_user.create.content.form.sections#left':
            access:
                template: '@SyliusAdminMcpServer/admin_user/form/sections/access.html.twig'
                priority: -50

        'sylius_admin.admin_user.update.content.form.sections#left':
            access:
                template: '@SyliusAdminMcpServer/admin_user/form/sections/access.html.twig'
                priority: -50
